/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Databasechangelog {
  author: string;
  comments: string | null;
  contexts: string | null;
  dateexecuted: Timestamp;
  deploymentId: string | null;
  description: string | null;
  exectype: string;
  filename: string;
  id: string;
  labels: string | null;
  liquibase: string | null;
  md5sum: string | null;
  orderexecuted: number;
  tag: string | null;
}

export interface Databasechangeloglock {
  id: number;
  locked: boolean;
  lockedby: string | null;
  lockgranted: Timestamp | null;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  id: string;
  secretHash: Buffer;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  nickname: string;
  password: string;
  role: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  databasechangelog: Databasechangelog;
  databasechangeloglock: Databasechangeloglock;
  session: Session;
  user: User;
}
